Feature/secondary button variant
FatimaGC/Portfolio pull request #14
Opened 2023-04-18 14:20 UTC by FatimaGC

2023-05-02 23:30 UTC, FatimaGC commented
@kee-oth Do you think I'm good to merge this?

2023-05-03 01:37 UTC, kee-oth commented
@FatimaGC 

I'm seeing some differences between the Primary and Secondary buttons:

1. Primary is rounded while secondary is squared off
2. Secondary "border" (it's actually an outline) makes the overall visual dimensions of the button larger. I recommend using the border property for this instead of outline. You can't make an outline rounded and border actually counts for the size of the button, which we'd want for this (otherwise, other elements will visually overlap with the button since the outline doesn't take up "physical" space, other elements act like it's not even there)
3. The hover state of the secondary button looks odd because of the outline not being rounded.

Primary
<img width="163" alt="Screenshot 2023-05-02 at 7 31 04 PM" src="https://user-images.githubusercontent.com/83618848/235817849-497526df-ab9b-4074-9ae6-bb7ce584ced3.png">

Secondary
<img width="179" alt="Screenshot 2023-05-02 at 7 31 15 PM" src="https://user-images.githubusercontent.com/83618848/235817881-f527fc9c-5001-4715-84f3-e2362bb00f5e.png">

Secondary hover
<img width="169" alt="Screenshot 2023-05-02 at 7 36 57 PM" src="https://user-images.githubusercontent.com/83618848/235818319-560c537a-c6e0-43c3-8227-1fd8b9ab0962.png">

2023-05-03 15:01 UTC, kee-oth commented
@FatimaGC There's also no shadow on secondary variant. Let's make sure that it's there for all the variants 👍

2023-05-04 01:43 UTC, FatimaGC commented
@kee-oth I checked and this is how things are looking on my end:

Secondary
<img width="407" alt="Screenshot 2023-05-03 at 7 39 50 PM" src="https://user-images.githubusercontent.com/73245376/236090718-cbb762b2-71be-49a7-a668-e2e207966169.png">

Secondary Hover 
<img width="456" alt="Screenshot 2023-05-03 at 7 39 55 PM" src="https://user-images.githubusercontent.com/73245376/236090797-2be2de8e-7729-401d-8198-2c32c1632ad3.png">

Not sure why there's a discrepancy

2023-05-05 03:44 UTC, kee-oth commented
@FatimaGC 

Looking better! But the buttons are different sizes, let's figure out what's going on there and fix it:

Primary
<img width="495" alt="Screenshot 2023-05-04 at 9 43 29 PM" src="https://user-images.githubusercontent.com/83618848/236373494-f0bac9e2-85a9-4547-a330-9acba45841b0.png">

Secondary
<img width="523" alt="Screenshot 2023-05-04 at 9 43 52 PM" src="https://user-images.githubusercontent.com/83618848/236373529-775f4a3d-c8cf-40d7-b0a3-81eac8522548.png">

2023-05-06 19:54 UTC, FatimaGC commented
> @FatimaGC
> 
> Looking better! But the buttons are different sizes, let's figure out what's going on there and fix it. Notice how the dimensions of the grid/box the same but in the Secondary button the border is on the _outside_ of the lines while on the Primary button the border is on the _inside_:
> 
> Primary <img alt="Screenshot 2023-05-04 at 9 43 29 PM" width="495" src="https://user-images.githubusercontent.com/83618848/236373494-f0bac9e2-85a9-4547-a330-9acba45841b0.png">
> 
> Secondary <img alt="Screenshot 2023-05-04 at 9 43 52 PM" width="523" src="https://user-images.githubusercontent.com/83618848/236373529-775f4a3d-c8cf-40d7-b0a3-81eac8522548.png">

@kee-oth Is the solution to this to add `box-sizing: border-box` to `.button` class?

2023-05-11 03:56 UTC, kee-oth requested changes

2023-05-11 03:56 UTC, kee-oth commented on src/components/Button/styles.css
> +  border: 2px solid var(--buttonColor--primary);
Let's alphabetically sort this property 🔤

2023-05-11 03:57 UTC, kee-oth commented
@FatimaGC Looks good to merge after that one change 💪

2023-05-14 00:03 UTC, merged